import random

sentences = [
    "Use the present simple tense to describe habitual actions, but use the present continuous tense to describe actions happening now.",
    "Use the past simple tense to describe completed actions in the past, but use the past continuous tense to describe actions that were in progress at a specific time in the past.",
    "Use the present perfect tense to describe actions that started in the past and continue up to the present, but use the past perfect tense to describe actions that were completed before another action in the past.",
    "Use the future simple tense to describe actions that will happen in the future, but use the future continuous tense to describe actions that will be in progress at a specific time in the future.",
    "Use the future perfect tense to describe actions that will be completed before another action in the future.",
    "Use the passive voice to emphasize the action rather than the subject, but use the active voice to emphasize the subject rather than the action.",
    "Use the subjunctive mood to express hypothetical or contrary-to-fact situations, but use the indicative mood to express factual situations.",
    "Use the conditional mood to express hypothetical situations, but use the indicative mood to express factual situations.",
    "Use the gerund form (-ing) to describe actions as nouns, but use the infinitive form (to + verb) to describe actions as verbs.",
    "Use the participle form (-ing or -ed) to describe actions as adjectives, but use the adverb form (-ly) to describe actions as adverbs.",
    "Use the comparative form (-er) to compare two things, but use the superlative form (-est) to compare three or more things.",
    "Use the definite article 'the' to refer to a specific noun, but use the indefinite articles 'a' or 'an' to refer to a non-specific noun.",
    "Use the possessive form ('s or s') to indicate ownership, but use the plural form (s') to indicate multiple owners.",
    "Use the preposition 'of' to indicate possession, but use the preposition 'for' to indicate purpose.",
    "Use the preposition 'in' to indicate location, but use the preposition 'on' to indicate surface.",
    "Use the preposition 'at' to indicate time, but use the preposition 'in' to indicate a longer period of time.",
    "Use the preposition 'to' to indicate direction, but use the preposition 'toward' to indicate a general direction.",
    "Use the preposition 'by' to indicate the agent of a passive sentence, but use the preposition 'with' to indicate the instrument of an action.",
    "Use the coordinating conjunctions 'and,' 'or,' and 'but' to connect words, phrases, or clauses of equal importance, but use the subordinating conjunctions 'because,' 'although,' and 'if' to connect clauses of unequal importance.",
    "Use the correlative conjunctions 'either...or,' 'neither...nor,' and 'both...and' to connect two words or phrases of equal importance.",
    "Use the interjection 'oh' to express surprise or emotion, but use the interjection 'well' to indicate a change of topic or thought.",
    "Use the adverb 'too' to indicate excess, but use the adverb 'enough' to indicate sufficiency.",
    "Use the adverb 'just' to indicate a recent action, but use the adverb 'merely' to indicate a small action.",
    "Use the adverb 'even' to indicate a surprising or unexpected action.",
    "Use the adverb 'soon' to indicate a near future action, but use the adverb 'later' to indicate a more distant future action.",
    "Use the adverb 'here' to indicate a specific location, but use the adverb 'there' to indicate a general location.",
    "Use the adverb 'now' to indicate the present moment, but use the adverb 'then' to indicate a past or future moment.",
    "Use the adverb 'ago' to indicate a past moment, but use the adverb 'since' to indicate a past moment that continues to the present.",
    "Use the adverb 'before' to indicate a past moment, but use the adverb 'after' to indicate a future moment.",
    "Use the adverb 'together' to indicate a group action, but use the adverb 'separately' to indicate individual actions.",
    "Use the adverb 'fast' to indicate speed, but use the adverb 'hard' to indicate difficulty.",
    "Use the adverb 'well' to indicate health or skill, but use the adverb 'good' to indicate quality.",
    "Use the adverb 'always' to indicate a consistent action, but use the adverb 'usually' to indicate a frequent action.",
    "Use the adverb 'sometimes' to indicate an occasional action, but use the adverb 'rarely' to indicate a seldom action.",
    "Use the adverb 'very' to intensify an adjective or adverb, but use the adverb 'quite' to indicate a high degree of something.",
    "Use the adverb 'just' to indicate a recent action, but use the adverb 'already' to indicate an action that has already happened.",
    "Use the adverb 'yet' to indicate an action that has not happened, but use the adverb 'still' to indicate an action that is ongoing.",
    "Use the adverb 'even' to indicate a surprising or unexpected action, but use the adverb 'only' to indicate a limited or exclusive action.",
    "Use the adverb 'never' to indicate a complete lack of an action, but use the adverb 'hardly' to indicate a small amount of an action.",
    "Use the adverb 'so' to indicate a result, but use the adverb 'such' to indicate a quality.",
    "Use the adverb 'yet' to indicate an action that has not happened, but use the adverb 'still' to indicate an action that is ongoing.",
    "Use the adverb 'even' to indicate a surprising or unexpected action."
    "Use the adverb 'soon' to indicate a near future action, but use the adverb 'later' to indicate a more distant future action.",
    "Use the adverb 'here' to indicate a specific location, but use the adverb 'there' to indicate a general location.",
    "Use the adverb 'now' to indicate the present moment, but use the adverb 'then' to indicate a past or future moment.",
    "Use the adverb 'ago' to indicate a past moment, but use the adverb 'since' to indicate a past moment that continues to the present.",
    "Use the adverb 'before' to indicate a past moment, but use the adverb 'after' to indicate a future moment.",
    "Use the adverb 'together' to indicate a group action, but use the adverb 'separately' to indicate individual actions.",]


random_tip = random.choice(sentences)
print(random_tip)